[project]
name = "asvab-anypct"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.40.0",
    "cyclopts>=3.1.2",
    "gumpython>=0.3.0",
    "sh>=2.1.0",
    "tqdm>=4.67.1",
]
